service: et-bot
provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-1
  environment:
    TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN}
functions:
  etbot:
    name: etbot-handler
    handler: handler.handler
    memorySize: 128
